### ISSUE TITLE
mac 版本？

### ISSUE THREAD

**Issue by xirwajim** [yingzk/zc-downloader#1]
只有 windows 版本么？我需要 mac 版本

**Comment by yingzk** [comment]
不好意思，暂时没有mac版本，会尽量做出来

**Comment by yingzk** [comment]
已加上Mac版本：https://github.com/yingzk/zc-downloader/releases/download/1.2/Mac.zip @xirwajim

**Comment by xirwajim** [comment]
@yingzk 好的 谢谢了
